### ISSUE TITLE
Option to make popout window property to "Normal window" 

### ISSUE THREAD

**Issue by datamaskinen** [ettoolong/MaximizeVideo#52]
##feature request

Hi,
There would be great if there was an option to check for making the popup window a normal window as of now it gets the property 'Dialog window' This would help other kwin scripts to treat it better as a normal window on the desktop

**Comment by ettoolong** [comment]
Hi @datamaskinen, can you check if it's related to this issue? ettoolong/PopupWindow#6

**Comment by datamaskinen** [comment]
I think it might be related.
It is not the same problem i have but i think that it is caused by the same origin.

I use KDE on linux and have a Kwin.scipt for making all windows have a gap with some pixels between my windows and as the popup window from the video gets the 'window property' 'window type = Dialog window' instead of 'window type = Normal window' it is not getting affected.

**Comment by datamaskinen** [comment]
here is a xdrop on the popup...
$ xprop | grep -i Dialog
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG


And here is on normal firefox window
$ xprop | grep -i normal
                window state: Normal
                Initial state is Normal State.
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
WM_NORMAL_HINTS(WM_SIZE_HINTS):

I think this is the part that is the imprtant
popup:
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG

Normal window:
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL

**Comment by ettoolong** [comment]
Thanks! @datamaskinen, check this issue: ettoolong/PopupWindow#11
The problem is I can't reproduce this issue on my environment now.
According [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/CreateType) document, the window type can be **popup** or **panel**.

Maybe you can help me test if I change the window type from **popup** to **panel** it will fix the problem. 🤔

How to:
1. Clone this repo, and modify **background.js** in folder, replace all `'popup'` to `'panel'`, then save file.
2. Check [this](https://developer.mozilla.org/en-US/docs/Tools/about:debugging) document, open the about:debugging page, select **This Firefox** item at side menu, click **Load Temporary Add-on** button.
3. Select the **manifest.json** in folder
4. Test it.

**Comment by datamaskinen** [comment]
ok i will try .... just give me some day and i will return.....

**Comment by datamaskinen** [comment]
hmmm is it not in this?
https://github.com/ettoolong/PopupWindow/blob/master/background.js

But it say normal there

**Comment by datamaskinen** [comment]
aaa ok it will get all the panels and shit ..... so let's leave this then .... we can close it ...

**Comment by ettoolong** [comment]
So... what is the conclusion? change **popup** to **panel** can fix this issue?

**Comment by datamaskinen** [comment]
no it was the same behavior
